### ISSUE TITLE
Кодировка файла описания ломается

### ISSUE THREAD

**Issue by realbsb** [iyudincev/FileTags#1]
Игорь, здравствуйте!
Похоже, в FAR description сейчас в UTF-8 и при первом добавлении тега ломается все существующие описания

**Comment by iyudincev** [comment]
Кодировка файлов описаний задаётся в настройках FAR (Параметры — Описания файлов) По умолчанию описания сохраняются в OEM-кодировке.

**Comment by realbsb** [comment]
Вот с такими настройками ломает:
Устанавливать атрибут "Скрытый" на новые списки описаний = on
Обновлять файл описаний с атрибутом "Только для чтения" = off
Позиция новых описаний в строке = 0
Обновлять, если они выводятся на экран = select
Использовать кодовую страницу ANSI по умолчанию = off
Сохранять в UTF-8 = on

Как повторить:
1. Сначала добавить рандомное описание по Ctrl+Z в кириллице
2. Запустить плагин и попробовать добавить тег (не обязательно для конкретного файла - ломает все)

**Comment by iyudincev** [comment]
https://github.com/iyudincev/FileTags/releases/tag/untagged-8abf7697083cfc28cc74

**Comment by iyudincev** [comment]
https://github.com/iyudincev/FileTags/releases/tag/1.7
